/// App-chrome strings (corpus text is localized in the data files).
/// Adding a language = adding entries here, never a schema change.
class S {
  final String lang;
  const S(this.lang);

  static const _en = <String, String>{
    'appName': 'morphcook',
    'tagline': 'the same dish exists for every body',
    'navHome': 'home',
    'navSearch': 'search',
    'navCookbook': 'cookbook',
    'navPlan': 'plan',
    'navSettings': 'settings',
    'featuredToday': 'featured today',
    'fromTheKitchen': 'from the kitchen',
    'editionFor': 'edition for',
    'yourCookbook': 'your cookbook',
    'cookbookEmpty': 'nothing saved yet.\nfind a dish & make it yours.',
    'cookbookHint': 'you save a specific variant — your döner, not a döner.',
    'saved': 'saved',
    'save': 'save',
    'searchHint': 'search dishes, ingredients, moods…',
    'searchEmpty': 'no recipes found for',
    'searchEmptyNote': 'we wrote it down — your wish helps us decide what to cook up next.',
    'filters': 'filters',
    'diet': 'diet',
    'effort': 'effort',
    'calorieLevel': 'calorie level',
    'time': 'time',
    'ingredients': 'ingredients',
    'method': 'method',
    'macros': 'macros',
    'perServing': 'per serving',
    'servings': 'servings',
    'minutes': 'min',
    'calories': 'kcal',
    'protein': 'protein',
    'carbs': 'carbs',
    'fat': 'fat',
    'noVariantNote': 'no version yet for',
    'comboUnavailable': 'not written yet — maybe soon',
    'outsideProfile':
        'this version sits outside your profile — yours to cook anyway',
    'outsideProfileCount': 'versions outside your profile',
    'outsideCalories': 'outside your calorie target',
    'showAnyway': 'show versions outside my target',
    'startCooking': 'start cooking',
    'resumeCooking': 'resume cooking',
    'step': 'step',
    'of': 'of',
    'startTimer': 'start timer',
    'pause': 'pause',
    'resume': 'resume',
    'timerDone': 'time! next move.',
    'done': 'done',
    'finishCooking': 'finish',
    'cookedIt': 'that\'s dinner. well done.',
    'cookAgainNote': 'logged to your history.',
    'backToRecipe': 'back to the recipe',
    'quickTapHint': 'tap anywhere on the step to go forward',
    'addToList': 'add to shopping list',
    'addedToList': 'added to your shopping list',
    'shoppingList': 'shopping list',
    'shoppingEmpty': 'list is empty.\nadd a recipe or plan your week.',
    'clearChecked': 'clear checked',
    'clearAll': 'clear all',
    'mealPlan': 'meal plan',
    'week': 'week',
    'breakfast': 'breakfast',
    'lunch': 'lunch',
    'dinner': 'dinner',
    'mon': 'mon', 'tue': 'tue', 'wed': 'wed', 'thu': 'thu',
    'fri': 'fri', 'sat': 'sat', 'sun': 'sun',
    'planEmptySlot': 'tap to plan',
    'exportWeekToList': 'send week to shopping list',
    'weekExported': 'week sent to your shopping list',
    'pickRecipe': 'pick a recipe',
    'fromCookbook': 'from your cookbook',
    'fromSearch': 'from search',
    'removeFromSlot': 'remove',
    'settings': 'settings',
    'profile': 'profile',
    'yourName': 'your name',
    'language': 'language',
    'dietAllergies': 'diet & avoidances',
    'avoidClasses': 'avoid whole groups',
    'avoidSpecific': 'avoid specific ingredients',
    'avoidSpecificHint': 'type an ingredient — apples, cilantro…',
    'requiredAttributes': 'must-haves',
    'calorieTarget': 'calorie target per meal',
    'timeBudget': 'time budget',
    'noLimit': 'no limit',
    'preferredEffort': 'usual effort mood',
    'showVariantTags': 'show variant tags on cards',
    'adaptationPrefs': 'adaptation preferences',
    'accessibility': 'accessibility',
    'reduceMotion': 'reduce motion',
    'systemDefault': 'system default',
    'on': 'on',
    'off': 'off',
    'visualAlert': 'visual timer alert (flash)',
    'visualAlertHint': 'flashes the screen when a timer ends — for when sound isn\'t an option.',
    'quickTap': 'one-handed cook mode (tap to advance)',
    'quickTapSettingHint': 'a single tap on the step content goes to the next step.',
    'halalKosherNote': 'we say "halal-compatible" / "kosher-compatible ingredients" only. certification belongs to sourcing — slaughter, supervision — not to a recipe text.',
    'backup': 'backup & restore',
    'exportBackup': 'export backup',
    'importBackup': 'import backup',
    'backupPassword': 'backup password (optional)',
    'backupPasswordHint': 'encrypts the .json file with AES-256-GCM. the .gz stays plain. a forgotten password cannot be recovered.',
    'enterPassword': 'enter password',
    'importMerge': 'merge with my data',
    'importReplace': 'replace my data',
    'importDone': 'backup restored.',
    'shoppingInsights': 'shopping insights',
    'varietyScore': 'variety score',
    'uniqueIngredients': 'unique ingredients',
    'topIngredients': 'most added',
    'seasonal': 'by month',
    'insightsEmpty': 'no shopping history yet — add recipes to your list and this page starts telling stories.',
    'helpCenter': 'help center',
    'faqSearchHint': 'search the help center…',
    'all': 'all',
    'learnMore': 'learn more',
    'kitchenReference': 'kitchen reference',
    'whereToFind': 'where to find it',
    'storage': 'storage',
    'tips': 'tips',
    'resetApp': 'start over (erase everything)',
    'resetConfirm': 'erase profile, cookbook, plans, history? the recipes stay — they\'re part of the app.',
    'cancel': 'cancel',
    'erase': 'erase',
    'history': 'history',
    'historyEmpty': 'nothing cooked yet.',
    'obLanguageTitle': 'which language feels like home?',
    'obNameTitle': 'what should we call you?',
    'obNameHint': 'first name, nickname, anything',
    'obDietTitle': 'how do you eat?',
    'obDietSub': 'this never filters you out of a dish — it picks the version that\'s yours.',
    'obAllergyTitle': 'anything to keep out of the kitchen?',
    'obTargetsTitle': 'targets, gently',
    'obCalories': 'calories per meal',
    'obTime': 'minutes you usually have',
    'obConfirmTitle': 'your cookbook is ready',
    'obConfirmBody': 'every dish in here exists in a version written for you. not adapted. written.',
    'next': 'next',
    'back': 'back',
    'letsCook': 'open my cookbook',
    'skip': 'skip',
    'whyHidden': 'why is a recipe hidden?',
    'variantFor': 'as it exists for you',
    'otherVersions': 'every body\'s version',
    'cookMode': 'cook mode',
    'overTime': 'over your time budget',
    'avoidedHit': 'contains something you avoid',
    'missingMust': 'missing one of your must-haves',
  };

  static const _de = <String, String>{
    'appName': 'morphcook',
    'tagline': 'dasselbe Gericht gibt es für jeden Körper',
    'navHome': 'Start',
    'navSearch': 'Suche',
    'navCookbook': 'Kochbuch',
    'navPlan': 'Plan',
    'navSettings': 'Mehr',
    'featuredToday': 'heute im Blatt',
    'fromTheKitchen': 'aus der Küche',
    'editionFor': 'Ausgabe für',
    'yourCookbook': 'dein Kochbuch',
    'cookbookEmpty': 'noch nichts gespeichert.\nfinde ein Gericht & mach es zu deinem.',
    'cookbookHint': 'du speicherst eine bestimmte Variante — deinen Döner, nicht irgendeinen.',
    'saved': 'gespeichert',
    'save': 'speichern',
    'searchHint': 'Gerichte, Zutaten, Stimmungen…',
    'searchEmpty': 'keine Rezepte gefunden für',
    'searchEmptyNote': 'wir haben es notiert — dein Wunsch hilft uns beim nächsten Kochbuch-Update.',
    'filters': 'Filter',
    'diet': 'Ernährung',
    'effort': 'Aufwand',
    'calorieLevel': 'Kalorien-Level',
    'time': 'Zeit',
    'ingredients': 'Zutaten',
    'method': 'Zubereitung',
    'macros': 'Nährwerte',
    'perServing': 'pro Portion',
    'servings': 'Portionen',
    'minutes': 'Min.',
    'calories': 'kcal',
    'protein': 'Eiweiß',
    'carbs': 'Kohlenhydrate',
    'fat': 'Fett',
    'noVariantNote': 'noch keine Version für',
    'comboUnavailable': 'noch nicht geschrieben — vielleicht bald',
    'outsideProfile':
        'diese Version liegt außerhalb deines Profils — koch sie trotzdem',
    'outsideProfileCount': 'Versionen außerhalb deines Profils',
    'outsideCalories': 'außerhalb deines Kalorienziels',
    'showAnyway': 'Versionen außerhalb meines Ziels zeigen',
    'startCooking': 'loskochen',
    'resumeCooking': 'weiterkochen',
    'step': 'Schritt',
    'of': 'von',
    'startTimer': 'Timer starten',
    'pause': 'Pause',
    'resume': 'weiter',
    'timerDone': 'Zeit! nächster Zug.',
    'done': 'fertig',
    'finishCooking': 'fertig',
    'cookedIt': 'das war\'s. gut gemacht.',
    'cookAgainNote': 'in deiner Historie vermerkt.',
    'backToRecipe': 'zurück zum Rezept',
    'quickTapHint': 'tippe irgendwo auf den Schritt, um weiterzugehen',
    'addToList': 'auf die Einkaufsliste',
    'addedToList': 'zur Einkaufsliste hinzugefügt',
    'shoppingList': 'Einkaufsliste',
    'shoppingEmpty': 'Liste ist leer.\nfüg ein Rezept hinzu oder plane deine Woche.',
    'clearChecked': 'Erledigtes löschen',
    'clearAll': 'alles löschen',
    'mealPlan': 'Wochenplan',
    'week': 'Woche',
    'breakfast': 'Frühstück',
    'lunch': 'Mittag',
    'dinner': 'Abend',
    'mon': 'Mo', 'tue': 'Di', 'wed': 'Mi', 'thu': 'Do',
    'fri': 'Fr', 'sat': 'Sa', 'sun': 'So',
    'planEmptySlot': 'antippen & planen',
    'exportWeekToList': 'Woche auf die Einkaufsliste',
    'weekExported': 'Woche auf deine Einkaufsliste gelegt',
    'pickRecipe': 'Rezept auswählen',
    'fromCookbook': 'aus deinem Kochbuch',
    'fromSearch': 'aus der Suche',
    'removeFromSlot': 'entfernen',
    'settings': 'Einstellungen',
    'profile': 'Profil',
    'yourName': 'dein Name',
    'language': 'Sprache',
    'dietAllergies': 'Ernährung & Ausschlüsse',
    'avoidClasses': 'ganze Gruppen meiden',
    'avoidSpecific': 'einzelne Zutaten meiden',
    'avoidSpecificHint': 'Zutat eintippen — Äpfel, Koriander…',
    'requiredAttributes': 'Must-haves',
    'calorieTarget': 'Kalorienziel pro Mahlzeit',
    'timeBudget': 'Zeitbudget',
    'noLimit': 'kein Limit',
    'preferredEffort': 'übliche Aufwands-Stimmung',
    'showVariantTags': 'Varianten-Tags auf Karten zeigen',
    'adaptationPrefs': 'Anpassungs-Einstellungen',
    'accessibility': 'Barrierefreiheit',
    'reduceMotion': 'Bewegung reduzieren',
    'systemDefault': 'Systemstandard',
    'on': 'an',
    'off': 'aus',
    'visualAlert': 'visueller Timer-Alarm (Blitz)',
    'visualAlertHint': 'der Bildschirm blitzt auf, wenn ein Timer endet — falls Ton keine Option ist.',
    'quickTap': 'Einhand-Kochmodus (Tippen = weiter)',
    'quickTapSettingHint': 'ein Tipp auf den Schritt springt zum nächsten.',
    'halalKosherNote': 'wir sagen nur „halal-kompatible" / „koscher-kompatible Zutaten". Zertifizierung gehört zur Beschaffung — Schlachtung, Aufsicht — nicht zu einem Rezepttext.',
    'backup': 'Backup & Wiederherstellen',
    'exportBackup': 'Backup exportieren',
    'importBackup': 'Backup importieren',
    'backupPassword': 'Backup-Passwort (optional)',
    'backupPasswordHint': 'verschlüsselt die .json-Datei mit AES-256-GCM. die .gz bleibt unverschlüsselt. ein vergessenes Passwort ist nicht wiederherstellbar.',
    'enterPassword': 'Passwort eingeben',
    'importMerge': 'mit meinen Daten zusammenführen',
    'importReplace': 'meine Daten ersetzen',
    'importDone': 'Backup wiederhergestellt.',
    'shoppingInsights': 'Einkaufs-Einblicke',
    'varietyScore': 'Vielfalts-Score',
    'uniqueIngredients': 'verschiedene Zutaten',
    'topIngredients': 'am häufigsten dabei',
    'seasonal': 'nach Monat',
    'insightsEmpty': 'noch keine Einkaufshistorie — leg Rezepte auf die Liste und diese Seite fängt an zu erzählen.',
    'helpCenter': 'Hilfe-Center',
    'faqSearchHint': 'im Hilfe-Center suchen…',
    'all': 'alle',
    'learnMore': 'mehr erfahren',
    'kitchenReference': 'Küchen-Lexikon',
    'whereToFind': 'wo du es findest',
    'storage': 'Lagerung',
    'tips': 'Tipps',
    'resetApp': 'neu anfangen (alles löschen)',
    'resetConfirm': 'Profil, Kochbuch, Pläne, Historie löschen? die Rezepte bleiben — sie gehören zur App.',
    'cancel': 'abbrechen',
    'erase': 'löschen',
    'history': 'Historie',
    'historyEmpty': 'noch nichts gekocht.',
    'obLanguageTitle': 'welche Sprache fühlt sich nach Zuhause an?',
    'obNameTitle': 'wie sollen wir dich nennen?',
    'obNameHint': 'Vorname, Spitzname, egal',
    'obDietTitle': 'wie isst du?',
    'obDietSub': 'das filtert dich nie aus einem Gericht heraus — es wählt die Version, die deine ist.',
    'obAllergyTitle': 'soll etwas aus der Küche bleiben?',
    'obTargetsTitle': 'Ziele, ganz entspannt',
    'obCalories': 'Kalorien pro Mahlzeit',
    'obTime': 'Minuten, die du meistens hast',
    'obConfirmTitle': 'dein Kochbuch ist bereit',
    'obConfirmBody': 'jedes Gericht hier gibt es in einer Version, die für dich geschrieben wurde. nicht angepasst. geschrieben.',
    'next': 'weiter',
    'back': 'zurück',
    'letsCook': 'mein Kochbuch öffnen',
    'skip': 'überspringen',
    'whyHidden': 'warum ist ein Rezept versteckt?',
    'variantFor': 'so, wie es für dich existiert',
    'otherVersions': 'die Versionen aller Körper',
    'cookMode': 'Kochmodus',
    'overTime': 'über deinem Zeitbudget',
    'avoidedHit': 'enthält etwas, das du meidest',
    'missingMust': 'eins deiner Must-haves fehlt',
  };

  String call(String key) =>
      (lang == 'de' ? _de[key] : _en[key]) ?? _en[key] ?? key;
}
